### PR TITLE
Update D3D renderstate vars & sigs

### PR DESCRIPTION
**Pull request by RadWolfie**
All D3DRS_ prefix variables are converted to CamelCaps due to they are referring to hardcode addresses than offset index. This is to avoid confusion between offset index or enum which normally use all caps. Plus all of them are now dumped through symbol register callback function.

One other minor fix is the comment referring to `D3D__PDEVICE` which should be `D3D_g_pDevice`.

 This pull request make partial fix to #75 for move [VerifyAndFixDeferredRenderStateOffset](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/8b9b26b56efec864293ab7a296cd0bbae869b256/src/core/hle/D3D8/Direct3D9/RenderStates.cpp#L73) function into XbSymbolDatabase repo. However, I made improvised verification process into `manual_scan_section_dx8_VerifyRenderStateOffsets` function which make tasks more easier by update revised `DxbxRenderStateInfo`'s table.

The following changes are made to align with retail titles' compiled XDK build.
- manual_scan_section_dx8_register_D3DRS:
   Dependency of `D3DDevice_SetRenderState_Simple` symbol reference is requirement in order to find either `D3DDevice_SetRenderStateNotInline` symbol or `D3DDevice_SetRenderStateInline__ManualFindGeneric` identification reference.
   Afterward, it will always find D3D_g_RenderState symbol reference after either of two references above are found.
   While I continued researching, I notice deferred renderstate's offset is always the same. Yet, due to OOVPA reference obtain less than 4 bytes isn't possible. Therefore require separate manual work to obtain it through `pD3D_g_DeferredRenderStateOffset` variable.
   Used to find:
   - D3D_g_RenderState
   - D3D_g_DeferredRenderState
- manual_scan_section_dx8_register_D3DCRS:
   I can confirm `D3DDevice_SetRenderState_FillMode` signature is always found and according to DxbxRenderStateInfo's table is 3 indexes ahead of where complex renderstate offset is located.
   Used to find:
   - D3DRS_FillMode
   - D3DRS_BackFillMode
   - D3DRS_TwoSidedLighting
   - D3D_g_ComplexRenderState
   - D3DRS_PSTextureModes
- manual_scan_section_dx8_register_D3DRS_end_of_list:
   Using D3D_CommonSetDebugRegisters signature allow to find end of the renderstate's list which is `D3DRS_DoNotCullUncompressed`.
   Used to find:
   - D3D_g_pDevice
   - D3DRS_RopZCmpAlwaysRead
   - D3DRS_RopZRead
   - D3DRS_DoNotCullUncompressed

The rest of the D3DRS_ prefix variables are self assigned through `manual_scan_section_dx8_register_D3DRS_vars` function. If there is a derive mask set, it will not self assign and therefore require to receive manual registers from `XbSymbolContext_RegisterXRefs` function.

All titles I own are passing unit test except for one Xbox dashboard (b5659). Although, after rebase and re-ran test again with Xbox dashboard did not return any failure for second time.
<details>
<summary>Xbox dashboard (b5659) errors</summary>

```
ERROR  : Symbol registered does not match raw vs virtual xbox. Raw xbe: 166 - Sim xbox: 231
ERROR  : g_SymbolAddressesRaw is missing D3D8 (b0000) 0x00000790 -> D3DDevice__m_VertexShader_OFFSET
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2048) 0x00148b90 -> Lock2DSurface_16
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2024) 0x001488b0 -> Get2DSurfaceDesc_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x0014a409 -> CMiniport_GetDisplayCapabilities
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x00148e25 -> CMiniport_InitHardware
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2036) 0x001460d0 -> D3D_BlockOnResource_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2060) 0x00145c50 -> D3D_BlockOnTime_4
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x00144f50 -> D3D_DestroyResource__LTCG
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b5558) 0x00145e00 -> D3D_MakeRequestedSpace_8
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3901) 0x00140ce0 -> D3D_UpdateProjectionViewportTransform
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b5558) 0x00141e80 -> D3DDevice_AddRef
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x00141f20 -> D3DDevice_BlockUntilVerticalBlank
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1036) 0x001427a0 -> D3DDevice_Clear
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x00141540 -> D3DDevice_CopyRects
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b5344) 0x00144cd0 -> D3DDevice_CreateIndexBuffer2
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x001457f0 -> D3DDevice_CreateTexture2
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b5455) 0x00144bf0 -> D3DDevice_CreateVertexBuffer2
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x00144700 -> D3DDevice_CreateVertexShader
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1036) 0x00145510 -> D3DDevice_DrawIndexedVertices
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2048) 0x00145440 -> D3DDevice_DrawVertices_4
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x00145290 -> D3DDevice_DrawVerticesUP
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b4134) 0x0014eec0 -> D3DDevice_EnableOverlay
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x00140ff0 -> D3DDevice_GetDeviceCaps
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x00141ee0 -> D3DDevice_GetDisplayFieldStatus
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x00141010 -> D3DDevice_GetDisplayMode
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2024) 0x00140510 -> D3DDevice_GetViewportOffsetAndScale_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2048) 0x001440c0 -> D3DDevice_LoadVertexShader_0__LTCG_eax_Address_edx_Handle
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b4134) 0x00145f40 -> D3DDevice_MakeSpace
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b4627) 0x00142390 -> D3DDevice_PersistDisplay
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2024) 0x00142520 -> D3DDevice_SetFlickerFilter_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x00141df0 -> D3DDevice_SetIndices
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2024) 0x00141d50 -> D3DDevice_SetPalette_4
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2036) 0x0014a710 -> D3DDevice_SetPixelShader_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1036) 0x00140020 -> D3DDevice_SetRenderState_BackFillMode
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1052) 0x0013f780 -> D3DDevice_SetRenderState_CullMode
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x0013fd00 -> D3DDevice_SetRenderState_DoNotCullUncompressed
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x0013fb20 -> D3DDevice_SetRenderState_Dxt1NoiseEnable
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013f6a0 -> D3DDevice_SetRenderState_EdgeAntiAlias
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013ffd0 -> D3DDevice_SetRenderState_FillMode
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013f720 -> D3DDevice_SetRenderState_FogColor
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013f800 -> D3DDevice_SetRenderState_FrontFace
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x0013fab0 -> D3DDevice_SetRenderState_LineWidth
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013ff70 -> D3DDevice_SetRenderState_LogicOp
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1060) 0x0013fe30 -> D3DDevice_SetRenderState_MultiSampleAntiAlias
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1072) 0x0013feb0 -> D3DDevice_SetRenderState_MultiSampleMask
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x0013fdd0 -> D3DDevice_SetRenderState_MultiSampleMode
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b4034) 0x0013fe00 -> D3DDevice_SetRenderState_MultiSampleRenderTargetMode
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013f850 -> D3DDevice_SetRenderState_NormalizeNormals
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x0013fbe0 -> D3DDevice_SetRenderState_OcclusionCullEnable
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b4034) 0x00140170 -> D3DDevice_SetRenderState_PSTextureModes
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x0013fcc0 -> D3DDevice_SetRenderState_RopZCmpAlwaysRead
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x0013fce0 -> D3DDevice_SetRenderState_RopZRead
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1036) 0x0013ff10 -> D3DDevice_SetRenderState_SampleAlpha
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013f6e0 -> D3DDevice_SetRenderState_ShadowFunc
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x0013fc50 -> D3DDevice_SetRenderState_StencilCullEnable
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013f940 -> D3DDevice_SetRenderState_StencilEnable
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013f9d0 -> D3DDevice_SetRenderState_StencilFail
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1036) 0x0013fa50 -> D3DDevice_SetRenderState_TextureFactor
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1072) 0x00140080 -> D3DDevice_SetRenderState_TwoSidedLighting
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1036) 0x00140120 -> D3DDevice_SetRenderState_VertexBlend
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x0013fba0 -> D3DDevice_SetRenderState_YuvEnable
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013fd20 -> D3DDevice_SetRenderState_ZBias
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x0013f8a0 -> D3DDevice_SetRenderState_ZEnable
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1084) 0x001411c0 -> D3DDevice_SetRenderTarget
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x00142020 -> D3DDevice_SetScissors
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x00144210 -> D3DDevice_SetShaderConstantMode_0__LTCG_eax1
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1044) 0x00143f20 -> D3DDevice_SetStreamSource
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2036) 0x00141ba0 -> D3DDevice_SetTexture_4
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2036) 0x00140350 -> D3DDevice_SetTextureState_BorderColor_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2024) 0x001402e0 -> D3DDevice_SetTextureState_BumpEnv_8
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2036) 0x001403a0 -> D3DDevice_SetTextureState_ColorKeyColor_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2058) 0x001401d0 -> D3DDevice_SetTextureState_TexCoordIndex_4
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2060) 0x00141f50 -> D3DDevice_SetTile_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b5558) 0x00141870 -> D3DDevice_SetTransform_0__LTCG_eax1_edx2
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1036) 0x00144970 -> D3DDevice_SetVertexShader
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b4627) 0x00144ae0 -> D3DDevice_SetVertexShaderConstant1
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b4627) 0x00144b40 -> D3DDevice_SetVertexShaderConstant4
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1048) 0x00141980 -> D3DDevice_SetViewport
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2036) 0x00143c30 -> D3DDevice_Swap_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x0014ed50 -> D3DDevice_UpdateOverlay
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x001458a0 -> D3DBaseTexture_GetLevelCount
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b3911) 0x00145060 -> D3DResource_AddRef
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2024) 0x001450f0 -> D3DResource_GetType_0
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b4039) 0x00145170 -> D3DResource_IsBusy
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1036) 0x001450a0 -> D3DResource_Release
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x001458d0 -> D3DTexture_GetSurfaceLevel2
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x00144c40 -> D3DVertexBuffer_Lock2
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b1024) 0x00144ec0 -> D3DSurface_GetDesc
ERROR  : g_SymbolAddressesRaw is missing D3D8LTCG (b2048) 0x00144d10 -> Direct3D_CreateDevice_4
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x0014a409 -> CMiniport_GetDisplayCapabilities
ERROR  : g_SymbolAddresses is missing D3D8 (b5558) 0x00145e00 -> D3D_MakeRequestedSpace_8
ERROR  : g_SymbolAddresses is missing D3D8 (b3901) 0x00140ce0 -> D3D_UpdateProjectionViewportTransform
ERROR  : g_SymbolAddresses is missing D3D8 (b5558) 0x00141e80 -> D3DDevice_AddRef
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x00141f20 -> D3DDevice_BlockUntilVerticalBlank
ERROR  : g_SymbolAddresses is missing D3D8 (b5344) 0x00144cd0 -> D3DDevice_CreateIndexBuffer2
ERROR  : g_SymbolAddresses is missing D3D8 (b5455) 0x00144bf0 -> D3DDevice_CreateVertexBuffer2
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x00144700 -> D3DDevice_CreateVertexShader
ERROR  : g_SymbolAddresses is missing D3D8 (b4134) 0x0014eec0 -> D3DDevice_EnableOverlay
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x00140ff0 -> D3DDevice_GetDeviceCaps
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x00141ee0 -> D3DDevice_GetDisplayFieldStatus
ERROR  : g_SymbolAddresses is missing D3D8 (b4134) 0x00145f40 -> D3DDevice_MakeSpace
ERROR  : g_SymbolAddresses is missing D3D8 (b4627) 0x00142390 -> D3DDevice_PersistDisplay
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x0013fd00 -> D3DDevice_SetRenderState_DoNotCullUncompressed
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x0013fb20 -> D3DDevice_SetRenderState_Dxt1NoiseEnable
ERROR  : g_SymbolAddresses is missing D3D8 (b4034) 0x0013fe00 -> D3DDevice_SetRenderState_MultiSampleRenderTargetMode
ERROR  : g_SymbolAddresses is missing D3D8 (b4034) 0x00140170 -> D3DDevice_SetRenderState_PSTextureModes
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x0013fcc0 -> D3DDevice_SetRenderState_RopZCmpAlwaysRead
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x0013fce0 -> D3DDevice_SetRenderState_RopZRead
ERROR  : g_SymbolAddresses is missing D3D8 (b4627) 0x00144ae0 -> D3DDevice_SetVertexShaderConstant1
ERROR  : g_SymbolAddresses is missing D3D8 (b4627) 0x00144b40 -> D3DDevice_SetVertexShaderConstant4
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x001458a0 -> D3DBaseTexture_GetLevelCount
ERROR  : g_SymbolAddresses is missing D3D8 (b3911) 0x00145060 -> D3DResource_AddRef
ERROR  : g_SymbolAddresses is missing D3D8 (b4039) 0x00145170 -> D3DResource_IsBusy
```
</details>

~~After reading the error log for comparison, I notice there's some mix of D3D8 and D3D8LTCG symbols between the two. Which has relative to `D3DDevice_SetRenderState_` prefix function references.~~

~~At this time, I am placing this pull request to draft until above is resolve to either remove duplicate or improve signatures.~~
**EDIT:**
Xbox dashboard (b5659)'s issue is from upstream, not from this pull request since manual comparison shows all are there except for D3DDevice__m_VertexShader_OFFSET reference.

### CODE REVIEW

**Comment by RadWolfie** [comment]
Xbox dashboard (b5659)'s errors are relative to D3D8 and D3D8LTCG library flags been inserted into xbe file. It is not cause of issue by this pull request. Pulled out of draft stage and ready for final review & merge.

**Comment by RadWolfie** [comment]
I made some discovery that old signatures will report warnings about duplicate detection at different addresses. Please do not merge this until they are updated.

**Review by PatrickvL — APPROVED** [review]
Assuming this will be (or was already?) tested rigourously, this work looks quite good, as it replaces a badly hardcoded piece of junk with something much more refined. Nicely done!

**Comment by RadWolfie** [comment]
Yes, plus later commits after converted back to draft mode are mainly updating signatures to be less redundant and remove duplicates signatures. They had been tested through unit test with numerous of titles with find symbol name is properly found.

Plus D3DDevice_SetRenderState_FrontFace signatures were falsely double detected due to 3911's signature is identical to D3DDevice_SetRenderState_NormalizeNormals symbol.  However, this doesn't affect Cxbx-Reloaded luckily.

**Pull request merged**
