### PR TITLE
OOVPA : Various fixes D3D8 OOVPAs

### PR DESCRIPTION
**Pull request by jarupxx**
This pull request includes
- Fix issues #42. False positive in D3DDevice_SelectVertexShader_0 and D3DDevice_SetShaderConstantMode_0.
Fix false positive by adding retn opcode. However, possibly false negative due the LTCG signature changes length.
- Separate D3D8 4039 database.
- Add D3D8LTCG OOVPAs.

### CODE REVIEW

**Comment by PatrickvL** [comment]
Looks good to me!

**Comment by RadWolfie** [comment]
Hmm... something is off with 4039 titles. `D3DDevice_SetRenderTarget` is missing from this pull request's generated symbol cache file. I believe this pull request is valid since `D3DDevice_SetRenderTarget` was moved and remain unchanged. I'm requiring at least couple days to investigate source of cause before re-validate the pull request.

**Comment by jarupxx** [comment]
I have corrected the D3DDevice_SetRenderTarget regression you pointed out. Thank you.

**Comment by RadWolfie** [comment]
I'm a little concerned with starting offset only has one instead of usual of 2 or more for better lockdown. For now, I am approving this pull request since you have tested both non-LTCG and LTCG titles.

**Pull request merged**
